apiVersion: apps/v1
kind: Deployment
metadata:
    name: orders
spec:
    selector:
        matchLabels:
            app: orders
    template:
        metadata:
            labels:
                app: orders
        spec:
            containers:
                - name: orders
                  image: ranjankumar2000/orders
                  env:
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: env-vars
                                key: jwt-key
                      - name: SALT_ROUNDS
                        value: "13"
                      - name: DB_URL
                        value: "mongodb://orders-mongo-srv:27017/orders"
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: NATS_URL
                        value: "http://nats-srv:4222"
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
    name: orders-srv
spec:
    selector:
        app: orders
    ports:
        - port: 4000
          targetPort: 4000
