apiVersion: apps/v1
kind: Deployment
metadata:
    name: payments
spec:
    selector:
        matchLabels:
            app: payments
    template:
        metadata:
            labels:
                app: payments
        spec:
            containers:
                - name: payments
                  image: ranjankumar2000/payments
                  env:
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: env-vars
                                key: jwt-key
                      - name: STRIPE_SEC_KEY
                        valueFrom:
                            secretKeyRef:
                                name: stripe
                                key: sec-key
                      - name: SALT_ROUNDS
                        value: "13"
                      - name: DB_URL
                        value: "mongodb://payments-mongo-srv:27017/payments"
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: NATS_URL
                        value: "http://nats-srv:4222"
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
    name: payments-srv
spec:
    selector:
        app: payments
    ports:
        - port: 3000
          targetPort: 3000
          name: payments
          protocol: TCP
